spring.application.name=be

# 기본 실행 profile, 이후 dev로 연결
spring.profiles.active=local

# JPA 공통 설정
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 개발 중 임시
spring.jpa.hibernate.ddl-auto=update

# Firebase
firebase.service-account-path=classpath:firebase/firebase-service-account.json